### ISSUE TITLE
Question regarding Research Endpoint Access

### ISSUE THREAD

**Issue by DanielaSchacherer** [Google-Health/path-foundation#1]
Hello there, 

I wanted to explore your notebook: [path-foundation/notebooks/train_data_efficient_classifier_dicom.ipynb](https://github.com/Google-Health/path-foundation/blob/master/notebooks/train_data_efficient_classifier_dicom.ipynb), but found the links to the research endpoint access request broken. 
Could you let me know, where I can apply for that access? 

Best, 
Daniela

**Comment by nickgeorge** [comment]
Thanks a lot Daniela!  Fix incoming...

**Comment by nickgeorge** [comment]
Fixed in latest push!  thanks again.
